#include <iostream>
#include <random>
#include <cmath>
#include <complex>
#include <stdio.h>
#include <algorithm>
#include <array>
#include <vector>

struct next_event{
  double shortest_distance_to_next_event;
  int vetoing_index;
};


struct next_event get_next_kinetic_event(int active_particle_index, int number_of_quantum_particles, int number_of_timeslices, 
    double active_particle_position, double east_neighbour_position, double west_neighbour_position, double mass,
    double timestep, int movement_direction){

    struct next_event e;
    
    double shortest_distance_to_next_kinetic_event = 1.0e10;
    e.shortest_distance_to_next_event = 1.0e10;
    e.vetoing_index = 0;


    int vetoing_index = 0;
    double initial_position = active_particle_position;
    for (int neighbour = 0; neighbour < 2; neighbour++){
        std::minstd_rand gen(std::random_device{}());
        std::uniform_real_distribution<double> dist(0.0, 1.0);
        // Use dist to transform the random unsigned int generated by gen into a 
        // double in [0.0, 1.0). Each call to dist(gen) generates a new random double.
        double uphill_energy =  log(dist(gen));

        double neighbour_position;
        int possible_veto;
        if (neighbour == 0){
            neighbour_position = west_neighbour_position;
            possible_veto = get_west_worldline_neighbour(active_particle_index, number_of_quantum_particles,
                        number_of_timeslices);
        }
        else {
            neighbour_position = east_neighbour_position;
            possible_veto = get_east_worldline_neighbour(active_particle_index, number_of_quantum_particles,
                        number_of_timeslices);
        }

        double intermediate_position;
        double bottom_of_well = neighbour_position;
        if((movement_direction > 0  && initial_position < bottom_of_well)
        || (movement_direction < 0 && initial_position > bottom_of_well)){
            intermediate_position = bottom_of_well;
        }
        else {
            intermediate_position = initial_position;
        }

        double initial_action = 0.5 * (mass / timestep) * pow((intermediate_position - neighbour_position), 2);
        double final_action = uphill_energy + initial_action;

        double a = 0.5 * mass / timestep;
        double b = - mass / timestep * neighbour_position;
        double c = a * pow(neighbour_position, 2) - final_action;

        std::array<std::complex<double>, 2> roots_arr; //pointer to adress of roots array returned from root-finding 
        roots_arr = get_quadratic_roots(a, b, c);

        std::array<double, 2> quadratic_roots;
        for(int i = 0; i < 2; i++){
            quadratic_roots.at(i) = real(roots_arr.at(i));
        }
        double final_position = get_final_position_of_single_well_event(movement_direction, quadratic_roots);

        double distance_to_candidate_kinetic_event = abs(final_position - initial_position);

        double shortest_distance_to_next_kinetic_event;
        if (distance_to_candidate_kinetic_event < shortest_distance_to_next_kinetic_event){
            e.shortest_distance_to_next_event = distance_to_candidate_kinetic_event;
            e.vetoing_index = possible_veto;
        } 
    }
  return e;

}

struct next_event get_next_event(int active_particle_index, int number_of_quantum_particles, int number_of_timeslices, 
    double active_particle_position, double east_neighbour_position, double west_neighbour_position, double mass,
    double timestep, int movement_direction, double anharmonicity, double omega_squared, double magnitude_of_double_well_position){

    struct next_event next_kinetic_event ;
    next_kinetic_event = get_next_kinetic_event(active_particle_index, number_of_quantum_particles, number_of_timeslices, 
        active_particle_position, east_neighbour_position, west_neighbour_position, mass, timestep, movement_direction);
    
    struct next_event next_potential_event;
    next_potential_event.shortest_distance_to_next_event = 1.0e10;
    next_potential_event.vetoing_index = 0;

    struct next_event shortest_event;
    shortest_event.shortest_distance_to_next_event = next_kinetic_event.shortest_distance_to_next_event;
    shortest_event.vetoing_index = next_kinetic_event.vetoing_index;

    double initial_position = active_particle_position;
    std::minstd_rand gen(std::random_device{}());
    std::uniform_real_distribution<double> dist(0.0, 1.0);
        // Use dist to transform the random unsigned int generated by gen into a 
        // double in [0.0, 1.0). Each call to dist(gen) generates a new random double.
    double uphill_energy =  log(dist(gen));
    double bottom_of_well;

    if(anharmonicity == 0.0 || omega_squared ==0.0){
        bottom_of_well = 0.0;
    }
    else{
        if(initial_position != 0.0){
            bottom_of_well = magnitude_of_double_well_position * (initial_position / initial_position);
        }
        else{
            if(movement_direction > 0){
                bottom_of_well = magnitude_of_double_well_position;
            }
            else{
                bottom_of_well = -magnitude_of_double_well_position;
            }
        }
    }

    double intermediate_position;
    if ((movement_direction > 0  && initial_position < bottom_of_well)
        || (movement_direction < 0 && initial_position > bottom_of_well)){
        intermediate_position = bottom_of_well;
    }
    else{
        intermediate_position = initial_position;
    }

    double initial_action = 0.5 * mass * timestep * omega_squared * pow(intermediate_position, 2)
                            + timestep * anharmonicity * pow(intermediate_position, 4);
    double final_action = uphill_energy + initial_action;

    std::vector<std::complex<double>> roots_vect; 
    if(anharmonicity == 0){
        
        roots_vect = get_harmonic_potential_roots(mass, timestep, omega_squared, final_action);
    }
    else{
        roots_vect = get_anharmonic_potential_roots(mass, timestep, anharmonicity, omega_squared, final_action);
    }
    double final_position;

    if(anharmonicity > 0.0 > omega_squared){
        bool real_roots = check_all_roots_real(roots_vect);
        if(real_roots){
            std::vector<double> real_roots_arr = get_real_elements(roots_vect);
            final_position = get_final_position_of_non_tunnel_event(intermediate_position, movement_direction, real_roots_arr);
        }
        else{
            if((movement_direction > 0 && intermediate_position > 0.0) ||
                (movement_direction < 0 && intermediate_position < 0.0)){
                std::vector<double> real_roots_arr = get_real_elements(roots_vect);
                final_position = get_final_position_of_single_well_event(movement_direction, real_roots_arr);
                }
            else{
                double remaining_barrier_height = get_barrier_height(intermediate_position, timestep, mass, anharmonicity,
                                                    omega_squared);
                bottom_of_well *= -1;
                intermediate_position = bottom_of_well;
                final_action -= remaining_barrier_height;
                roots_vect = get_anharmonic_potential_roots(mass, timestep, anharmonicity, omega_squared, final_action);
                bool real_roots = check_all_roots_real(roots_vect);
                std::vector<double> real_roots_arr = get_real_elements(roots_vect);
                if(real_roots){
                    final_position = get_final_position_of_non_tunnel_event(intermediate_position, movement_direction, real_roots_arr);
                }
                else{
                    final_position = get_final_position_of_single_well_event(movement_direction, real_roots_arr);
                }
            }
        }
    }
    else{
        final_position = get_final_position_of_single_well_event(movement_direction, roots_vect);
    }
    double distance_to_next_factor_event = abs(final_position - initial_position);
    next_potential_event.shortest_distance_to_next_event = distance_to_next_factor_event;
    next_potential_event.vetoing_index = active_particle_index;
    if(next_potential_event.shortest_distance_to_next_event < next_kinetic_event.shortest_distance_to_next_event){
        shortest_event.shortest_distance_to_next_event = next_potential_event.shortest_distance_to_next_event;
        shortest_event.vetoing_index = next_potential_event.vetoing_index;
    }

    return shortest_event;
}

double get_barrier_height(double position, double timestep, double mass, double anharmonicity, double omega_squared){
  return abs(-(timestep * anharmonicity * pow(position, 4) + 0.5 * mass * timestep * omega_squared * pow(position, 2)));
}

std::vector<double> get_real_elements(std::vector<std::complex<double>> complex_arr){

    std::vector<double> real_arr;
    for(int i = 0; i < complex_arr.size(); i++){
        std::complex<double> ith_root = complex_arr.at(i);
        if(ith_root.imag() == 0){
            real_arr.push_back(ith_root.real());
        }
    }

    return real_arr;

}

double get_final_position_of_non_tunnel_event(double position, int movement_direction, std::vector<double> roots){
    std::sort(roots.at(0), roots.at(3));

    if(position < 0.0){
        if(movement_direction > 0){
            return roots.at(1);
        }
        else{
            return roots.at(0);
        }
    }
    else{
        if(movement_direction > 0){
            return roots.at(3);
        }
        else{
            return roots.at(2);
        }
    }
}


bool check_all_roots_real(std::vector<std::complex<double>> roots){
    bool real_roots = true;
    for(int i = 0; i < 4; i++){
        std::complex<double> ith_root = roots.at(i); // dereferencing roots_ptr to access the value of array roots_ptr[i]
        if(ith_root.imag() != 0.0){
            real_roots = false;
        }
    }
    return real_roots;
}

std::vector<std::complex<double>>  get_harmonic_potential_roots(double mass, double timestep, double omega_squared, double final_action){
  
    std::array<std::complex<double>, 2> roots; 
    double a = 0.5 * mass * timestep * omega_squared;
    double b = 0.0;
    double c = -final_action;

    roots = get_quadratic_roots(a, b, c);
    std::vector<std::complex<double>> roots_vect(roots.begin(), roots.end());

    return roots;
}

std::vector<std::complex<double>> get_anharmonic_potential_roots(double mass, double timestep, double anharmonicity,
                      double omega_squared, double final_action){
    std::array<std::complex<double>, 2> roots_ptr; 
    std::array<std::complex<double>, 4> roots; 
    double a = timestep * anharmonicity;
    double b = 0.5 * mass * timestep * omega_squared;
    double c = -final_action;

    roots_ptr = get_quadratic_roots(a, b, c);

    roots.at(0) = sqrt(roots_ptr.at(0)); 
    roots.at(1) = -sqrt(roots_ptr.at(0));
    roots.at(2) = sqrt(roots_ptr.at(1)); 
    roots.at(3) = -sqrt(roots_ptr.at(1));

    std::vector<std::complex<double>> roots_vect(roots.begin(), roots.end());

    return roots_vect;
  
}


std::array<std::complex<double>, 2> get_quadratic_roots(double a, double b, double c){
    // complex type because we could sqrt a -ve number here
    std::array<std::complex<double>, 2> roots; 

    roots.at(0) = (-b + std::sqrt(std::complex<double>(pow(b, 2) - 4 * a * c))) / (2 * a);
    roots.at(1) = (-b - std::sqrt(std::complex<double>(pow(b, 2) - 4 * a * c))) / (2 * a);

    return roots;
}


double get_final_position_of_single_well_event(int movement_direction, std::array<double, 2> roots){
    if ((movement_direction > 0) && (roots.at(0) > roots.at(1))){
        return roots.at(0);
    }
    else if ((movement_direction > 0) && (roots.at(0) < roots.at(1))){
        return roots.at(1);
    }
    else if ((movement_direction < 0) && (roots.at(0) < roots.at(1))){
        return roots.at(0);
    }
    else{
        return roots.at(1);
    }
}

double get_final_position_of_single_well_event(int movement_direction, std::vector<double> roots){
    if(roots.size() == 2){
    if ((movement_direction > 0) && (roots.at(0) > roots.at(1))){
        return roots.at(0);
    }
    else if ((movement_direction > 0) && (roots.at(0) < roots.at(1))){
        return roots.at(1);
    }
    else if ((movement_direction < 0) && (roots.at(0) < roots.at(1))){
        return roots.at(0);
    }
    else{
        return roots.at(1);
    }
    }
    else{
    throw std::invalid_argument("roots should have length 2");
    }
}

int get_east_worldline_neighbour(int lattice_site_index, int number_of_quantum_particles, int number_of_timeslices){
    return (lattice_site_index + number_of_quantum_particles) %
              (number_of_timeslices * number_of_quantum_particles);
}

int get_west_worldline_neighbour(int lattice_site_index, int number_of_quantum_particles, int number_of_timeslices){
    return (lattice_site_index - number_of_quantum_particles) %
            (number_of_timeslices * number_of_quantum_particles);
}

int main() {

    return 0;
} 