from .sampler import Sampler
import numpy as np
import sys
sys.path.append("..")
from mediator.event_chain_mediator import EventChainMediator
from base.exceptions import ConfigurationError

class ActiveParticleSampler(Sampler):
    """
    Class for taking observations of the active particle within EventChainMediator.
    """
    def  __init__(self, output_directory: str):
        """
        The constructor of the PressureSampler class.

        Parameters
        ----------
        output_directory : str
            The filename onto which the sample is written at the end of the run.
        """
        super().__init__(output_directory)

    def get_empty_sample_array(self, total_number_of_iterations):
        """
        Generate array that stores the sample.

        Parameters
        ----------
        total_number_of_iterations : int
            The total number of iterations of the Markov chain.

        Returns
        -------
        numpy.ndarray
            Numpy array of zeros of the required structure.
        """
        # there are an average of 35.5 changes in active particle per sample taken, plus some extra to ensure no
        # overflow
        return np.zeros(((total_number_of_iterations + 1) * 36, 1)) 
    
    def get_observation(self, momenta, positions, potential, mediator):
        """
        Returns an observation of the system for the given particle momenta and positions.

        Parameters
        ----------
        momenta : None or numpy.ndarray
            None or a two-dimensional numpy array of size (number_of_particles, dimensionality_of_particle_space); each
            element is a float and represents one Cartesian component of the momentum of a single particle.
        positions : numpy.ndarray
            A two-dimensional numpy array of size (number_of_particles, dimensionality_of_particle_space); each element
            is a float and represents one Cartesian component of the position of a single particle. For Bayesian
            models, the entire positions array corresponds to the parameter; for the Ginzburg-Landau potential on a
            lattice, the entire positions array corresponds to the entire array of superconducting phase.
        potential : float or potential.potential.Potential
            If a float, the current value of the potential; otherwise, an instance of the chosen child class of
            potential.potential.Potential.

        Returns
        -------
        numpy.ndarray
            The observation.
        """
        if not isinstance(mediator, EventChainMediator):
            raise ConfigurationError("ActiveParticleSampler only available for EventChainMediator. Please use this" \
            "mediator in the configuration file.")
        else:
            return mediator.active_particle_index

    def output_sample(self, sample, temperature_index, checkpoint_index):
        """
        Following completion of the Markov chain, print the sample to the output file.

        Parameters
        ----------
        sample : numpy.ndarray
            The sample generated by the Markov chain.
        temperature_index : int
            The index of the iteration through the list sampling temperatures.
        checkpoint_index : int
            The index of the iteration through the list sampling checkpoints.
        """
        self._write_sample_to_file(sample, f"temperature_{temperature_index:02d}_checkpoint_{checkpoint_index:02d}_"
                                           f"sample_of_active_particles.npy")
        
        def get_sample(self, temperature_index, checkpoint_index):
            """
            In order to analyse the Markov chain in an external program, read the sample from the output file.

            Parameters
            ----------
            temperature_index : int
                The index of the iteration through the list sampling temperatures.

            Returns
            ----------
            numpy.ndarray
                The sample generated by the Markov chain.
            """
            return self._read_sample_from_file(
             f"temperature_{temperature_index:02d}__checkpoint_{checkpoint_index:02d}sample_of_potential.npy")