"""Module for the EventSampler class."""
from base.exceptions import ConfigurationError
from model_settings import number_of_particles, size_of_particle_space
from .sampler import Sampler
import numpy as np
from abc import ABCMeta, abstractmethod


class EventSampler(Sampler, metaclass=ABCMeta):
    """
    Abstract class for taking observations of the system at event times.
    """

    def __init__(self, output_directory: str):
        """
        The constructor of the EventSampler class.

        This class is designed for cooperative inheritance, meaning that it passes through all unused kwargs in the
        init to the next class in the MRO via super.

        Parameters
        ----------
        output_directory : str
            The filename onto which the sample is written at the end of the run.

        Raises
        ------
        base.exceptions.ConfigurationError
            If dimensionality_of_particle_space does not equal 1.
        """
        super().__init__(output_directory)

    def get_empty_sample_array(self, total_number_of_iterations):
        """
        Generate array that stores the sample.

        Parameters
        ----------
        total_number_of_iterations : int
            The total number of iterations of the Markov chain.

        Returns
        -------
        list
            Variable length array to account for random number of events.
        """
        return []

    def get_observation(self, momenta, positions, potential):
        """
        Returns an observation of the system for the given particle momenta and positions.

        Parameters
        ----------
        momenta : None or numpy.ndarray
            None or a two-dimensional numpy array of size (number_of_particles, dimensionality_of_particle_space); each
            element is a float and represents one Cartesian component of the momentum of a single particle.
        positions : numpy.ndarray
            A two-dimensional numpy array of size (number_of_particles, dimensionality_of_particle_space); each element
            is a float and represents one Cartesian component of the position of a single particle. For Bayesian
            models, the entire positions array corresponds to the parameter; for the Ginzburg-Landau potential on a
            lattice, the entire positions array corresponds to the entire array of superconducting phase.
        potential : float or potential.potential.Potential
            If a float, the current value of the potential; otherwise, an instance of the chosen child class of
            potential.potential.Potential.

        Returns
        -------
        float
            The observation of the particle positions at the event time.
        """
        raise NotImplementedError(f"Event samplers don't utilise get_observation. Use get_event_observation instead.")

    @abstractmethod
    def get_event_observation(self, momenta, positions, potential, active_particle_index, vetoing_index,
                              distance_to_next_event):
        """
        Returns an observation of the system at an event for the given particle momenta and positions.

        Parameters
        ----------
        momenta : None or numpy.ndarray
            None or a two-dimensional numpy array of size (number_of_particles, dimensionality_of_particle_space); each
            element is a float and represents one Cartesian component of the momentum of a single particle.
        positions : numpy.ndarray
            A two-dimensional numpy array of size (number_of_particles, dimensionality_of_particle_space); each element
            is a float and represents one Cartesian component of the position of a single particle. For Bayesian
            models, the entire positions array corresponds to the parameter; for the Ginzburg-Landau potential on a
            lattice, the entire positions array corresponds to the entire array of superconducting phase.
        potential : float or potential.potential.Potential
            If a float, the current value of the potential; otherwise, an instance of the chosen child class of
            potential.potential.Potential.
        active_particle_index : int
            The active particle index
        vetoing_index : int
            The index of the particle that triggers the event.
        distance_to_next_event : float
            Distance to next ECMC event.
        """
        raise NotImplementedError

    @abstractmethod
    def output_sample(self, sample, temperature_index, checkpoint_index):
        """
        Following completion of the Markov chain, print the sample to the output file.

        Parameters
        ----------
        sample : numpy.ndarray
            The sample generated by the Markov chain.
        temperature_index : int
            The index of the iteration through the list sampling temperatures.
        checkpoint_index : int
            The index of the iteration through the list sampling checkpoints.
        """
        raise NotImplementedError

    @abstractmethod
    def get_sample(self, temperature_index):
        """
        In order to analyse the Markov chain in an external program, read the sample from the output file.

        Parameters
        ----------
        temperature_index : int
            The index of the iteration through the list sampling temperatures.

        Returns
        ----------
        numpy.ndarray
            The sample generated by the Markov chain.
        """
        raise NotImplementedError
