"""Module for the HalfSystemDistanceVarianceSampler class."""
from base.exceptions import ConfigurationError
from model_settings import number_of_particles, size_of_particle_space
from .observation_sampler import ObservationSampler
import numpy as np


class HalfSystemDistanceVarianceSampler(ObservationSampler):
    """
    Class for taking observations of the variance of the half-system distance, defined as x_{i+N/2} - x_i - L/2.
    """

    def __init__(self):
        """
        The constructor of the HalfSystemDistanceVarianceSampler class.

        This class is designed for cooperative inheritance, meaning that it passes through all unused kwargs in the
        init to the next class in the MRO via super.

        Raises
        ------
        base.exceptions.ConfigurationError
            If dimensionality_of_particle_space does not equal 1.
        """
        super().__init__()
        for component in np.atleast_1d(size_of_particle_space):
            if component is None:
                raise ConfigurationError(f"Give a float for each component of size_of_particle_space in [ModelSettings]"
                                         f" when using {self.__class__.__name__} as {self.__class__.__name__} is "
                                         f"designed for toroidal systems.")

    def get_empty_sample_array(self, total_number_of_iterations):
        """
        Generate array that stores the sample.

        Parameters
        ----------
        total_number_of_iterations : int
            The total number of iterations of the Markov chain.

        Returns
        -------
        numpy.ndarray
            Numpy array of zeros of the required structure.
        """
        return np.zeros((total_number_of_iterations, 1))

    def get_observation(self, momenta, positions, potential):
        """
        Returns an observation of the system for the given particle momenta and positions.

        Parameters
        ----------
        momenta : None or numpy.ndarray
            None or a two-dimensional numpy array of size (number_of_particles, dimensionality_of_particle_space); each
            element is a float and represents one Cartesian component of the momentum of a single particle.
        positions : numpy.ndarray
            A two-dimensional numpy array of size (number_of_particles, dimensionality_of_particle_space); each element
            is a float and represents one Cartesian component of the position of a single particle. For Bayesian
            models, the entire positions array corresponds to the parameter; for the Ginzburg-Landau potential on a
            lattice, the entire positions array corresponds to the entire array of superconducting phase.
        potential : float or potential.potential.Potential
            If a float, the current value of the potential; otherwise, an instance of the chosen child class of
            potential.potential.Potential.

        Returns
        -------
        float
            The observation of the variance of the half-system distance.
        """
        half_system_dists = []
        for i in range(number_of_particles):
            j = int(i + number_of_particles / 2) % number_of_particles
            position_i, position_j = positions[i].copy(), positions[j].copy()
            if j < i:
                position_j += size_of_particle_space
            half_system_dists.append(position_j - position_i - size_of_particle_space / 2.0)
        return np.var(half_system_dists)

    def output_sample(self, sample, checkpoint_index, output_directory):
        """
        Following completion of the Markov chain, print the sample to the output file.

        Parameters
        ----------
        sample : numpy.ndarray
            The sample generated by the Markov chain.
        checkpoint_index : int
            The index of the iteration through the list sampling checkpoints.
        output_directory : str
            The name of the directory into which the sample file is written at the end of the run.
        """
        self._write_sample_to_file(sample, f"checkpoint_{checkpoint_index:02d}_sample_of_half_"
                                           f"system_distance_variance.npy", output_directory)

    def get_sample(self, checkpoint_index, output_directory):
        """
        In order to analyse the Markov chain in an external program, read the sample from the output file.

        Parameters
        ----------
        checkpoint_index : int
            The index of the iteration through the list sampling checkpoints.
        output_directory : str
            The name of the directory into which the sample file is written at the end of the run.

        Returns
        ----------
        numpy.ndarray
            The sample generated by the Markov chain.
        """
        return self._read_sample_from_file(
            f"checkpoint_{checkpoint_index:02d}_sample_of_half_system_distance_variance.npy", output_directory)
