"""Module for the MeanPositionSampler class."""
from .sampler import Sampler
from base.logging import log_init_arguments
from model_settings import dimensionality_of_particle_space
from abc import ABCMeta
import logging
import numpy as np


class MeanPositionSampler(Sampler, metaclass=ABCMeta):
    """
    Abstract class for taking observations of the mean particle positions.
    """

    def __init__(self, output_directory: str, **kwargs):
        """
        The constructor of the MeanPositionSampler class.

        This class is designed for cooperative inheritance, meaning that it passes through all unused kwargs in the
        init to the next class in the MRO via super.

        Parameters
        ----------
        output_directory : str
            The filename onto which the sample is written at the end of the run.
        kwargs : Any
            Additional kwargs which are passed to the __init__ method of the next class in the MRO.
        """
        super().__init__(output_directory, **kwargs)
        log_init_arguments(logging.getLogger(__name__).debug, self.__class__.__name__,
                           output_directory=output_directory)

    def get_empty_sample_array(self, total_number_of_iterations):
        """
        Generate array that stores the sample.

        Parameters
        ----------
        total_number_of_iterations : int
            The total number of iterations of the Markov chain.

        Returns
        -------
        numpy.ndarray
            Numpy array of zeros of the required structure.
        """
        return np.zeros((total_number_of_iterations + 1, dimensionality_of_particle_space))

    def output_sample(self, sample, temperature_index):
        """
        Following completion of the Markov chain, print the sample to the output file.

        Parameters
        ----------
        sample : numpy.ndarray
            The sample generated by the Markov chain.
        temperature_index : int
            The index of the iteration through the list sampling temperatures.
        """
        self._write_sample_to_file(sample, f"temperature_{temperature_index:02d}_sample_of_mean_positions.npy")

    def get_sample(self, temperature_index):
        """
        In order to analyse the Markov chain in an external program, read the sample from the output file.

        Parameters
        ----------
        temperature_index : int
            The index of the iteration through the list sampling temperatures.

        Returns
        ----------
        numpy.ndarray
            The sample generated by the Markov chain.
        """
        return self._read_sample_from_file(f"temperature_{temperature_index:02d}_sample_of_mean_positions.npy")
