"""Module for the MeanSquaredPositionSampler class."""
from .observation_sampler import ObservationSampler
import numpy as np

class MeanSquaredPositionSampler(ObservationSampler):
    """
    Class for taking observations of the mean squared particle positions without correcting for periodic boundaries.
    """

    def __init__(self, timestep: float = 0.1, x_shift: float = 0.0):
        """
        The constructor of the MeanSquaredPositionSampler class.

        Parameters
        ----------
        timestep : float
            The size of the time step.
        """
        super().__init__()
        self._timestep = timestep
        self._x_shift = x_shift

    def get_empty_sample_array(self, total_number_of_iterations):
        """
        Generate array that stores the sample.

        Parameters
        ----------
        total_number_of_iterations : int
            The total number of iterations of the Markov chain.

        Returns
        -------
        numpy.ndarray
            Numpy array of zeros of the required structure.
        """
        return np.zeros((total_number_of_iterations, 1))

    def get_observation(self, momenta, positions, potential):
        """
        Returns an observation of the system for the given particle momenta and positions.

        Parameters
        ----------
        momenta : None or numpy.ndarray
            None or a two-dimensional numpy array of size (number_of_particles, dimensionality_of_particle_space); each
            element is a float and represents one Cartesian component of the momentum of a single particle.
        positions : numpy.ndarray
            A one-dimensional numpy array of size (number_of_particles), indexed by time step; each element
            is a float and represents the position of the worldline at that time step.
        potential : float or potential.potential.Potential
            If a float, the current value of the potential; otherwise, an instance of the chosen child class of
            potential.potential.Potential.

        Returns
        -------
        numpy.ndarray
            The observation of the positions.
        """

        return np.mean(np.square(positions - self._x_shift))

    def output_sample(self, sample, checkpoint_index, output_directory):
        """
        Following completion of the Markov chain, print the sample to the output file.

        Parameters
        ----------
        sample : numpy.ndarray
            The sample generated by the Markov chain.
        checkpoint_index : int
            The index of the iteration through the list sampling checkpoints.
        output_directory : str
            The name of the directory into which the sample file is written at the end of the run.
        """
        self._write_sample_to_file(sample, f"checkpoint_{checkpoint_index:02d}"
                                           f"_sample_of_mean_squared_positions.npy", output_directory)

    def get_sample(self, checkpoint_index, output_directory):
        """
        In order to analyse the Markov chain in an external program, read the sample from the output file.

        Parameters
        ----------
        checkpoint_index : int
            The index of the iteration through the list sampling checkpoints.
        output_directory : str
            The name of the directory into which the sample file is written at the end of the run.

        Returns
        ----------
        numpy.ndarray
            The sample generated by the Markov chain.
        """
        return self._read_sample_from_file(
            f"checkpoint_{checkpoint_index:02d}_sample_of_mean_squared_positions.npy", output_directory)
