"""Module for the MinimumParticleSeparationSampler class."""
import numpy as np
from base.exceptions import ConfigurationError
from .observation_sampler import ObservationSampler
from base.vectors import get_shortest_vectors_on_torus
from model_settings import size_of_particle_space, number_of_particles


class MinimumParticleSeparationSampler(ObservationSampler):
    """
    Class for taking observations of the minimum particle-particle separation distance.
    """

    def __init__(self):
        """
        The constructor of the MinimumParticleSeparationSampler class.

        Raises
        ------
        base.exceptions.ConfigurationError
            If dimensionality_of_particle_space does not equal 1.
        """
        super().__init__()
        for component in np.atleast_1d(size_of_particle_space):
            if component is None:
                raise ConfigurationError(f"Give a float for each component of size_of_particle_space in [ModelSettings]"
                                         f" when using {self.__class__.__name__} as {self.__class__.__name__} is "
                                         f"designed for toroidal systems.")

    def get_empty_sample_array(self, total_number_of_iterations):
        """
        Generate array that stores the sample.

        Parameters
        ----------
        total_number_of_iterations : int
            The total number of iterations of the Markov chain.

        Returns
        -------
        numpy.ndarray
            Numpy array of zeros of the required structure.
        """
        return np.zeros((total_number_of_iterations, 1))

    def get_observation(self, momenta, positions, potential):
        """
        Returns an observation of the system for the given particle momenta and positions.

        Parameters
        ----------
        momenta : None or numpy.ndarray
            None or a two-dimensional numpy array of size (number_of_particles, dimensionality_of_particle_space); each
            element is a float and represents one Cartesian component of the momentum of a single particle.
        positions : numpy.ndarray
            A two-dimensional numpy array of size (number_of_particles, dimensionality_of_particle_space); each element
            is a float and represents one Cartesian component of the position of a single particle. For Bayesian
            models, the entire positions array corresponds to the parameter; for the Ginzburg-Landau potential on a
            lattice, the entire positions array corresponds to the entire array of superconducting phase.
        potential : float or potential.potential.Potential
            If a float, the current value of the potential; otherwise, an instance of the chosen child class of
            potential.potential.Potential.

        Returns
        -------
        float
            The observation of the minimum particle-particle separation distance.
        """
        # for particle_index in range(number_of_particles):
        #    neg_neighbour_index = (particle_index - 1) % number_of_particles
        #    neg_neighbour_position = positions[neg_neighbour_index].copy()
        #    if particle_index == 0:
        #        neg_neighbour_position -= size_of_particle_space
        #    min_separation = min(min_separation, abs(positions[particle_index] - neg_neighbour_position))
        displacements = positions[:, 0] - np.roll(positions, 1)[:, 0]
        return np.min(np.abs(get_shortest_vectors_on_torus(displacements)))

    def output_sample(self, sample, checkpoint_index, output_directory):
        """
        Following completion of the Markov chain, print the sample to the output file.

        Parameters
        ----------
        sample : numpy.ndarray
            The sample generated by the Markov chain.
        checkpoint_index : int
            The index of the iteration through the list sampling checkpoints.
        output_directory : str
            The name of the directory into which the sample file is written at the end of the run.
        """
        self._write_sample_to_file(sample, f"checkpoint_{checkpoint_index:02d}_sample_of_minimum_particle_"
                                           f"separation.npy", output_directory)

    def get_sample(self, checkpoint_index, output_directory):
        """
        In order to analyse the Markov chain in an external program, read the sample from the output file.

        Parameters
        ----------
        checkpoint_index : int
            The index of the iteration through the list sampling checkpoints.
        output_directory : str
            The name of the directory into which the sample file is written at the end of the run.

        Returns
        ----------
        numpy.ndarray
            The sample generated by the Markov chain.
        """
        return self._read_sample_from_file(
            f"checkpoint_{checkpoint_index:02d}_sample_of_minimum_particle_separation.npy", output_directory)
