"""Module for the PositionSampler class."""
from .sampler import Sampler
from model_settings import number_of_particles, dimensionality_of_particle_space
from abc import ABCMeta
import numpy as np


class PositionSampler(Sampler, metaclass=ABCMeta):
    """
    Abstract class for taking observations of the particle positions.
    """

    def __init__(self, output_directory: str, **kwargs):
        """
        The constructor of the PositionSampler class.

        This class is designed for cooperative inheritance, meaning that it passes through all unused kwargs in the
        init to the next class in the MRO via super.

        Parameters
        ----------
        output_directory : str
            The filename onto which the sample is written at the end of the run.
        kwargs : Any
            Additional kwargs which are passed to the __init__ method of the next class in the MRO.
        """
        super().__init__(output_directory, **kwargs)

    def get_empty_sample_array(self, total_number_of_iterations):
        """
        Generate array that stores the sample.

        Parameters
        ----------
        total_number_of_iterations : int
            The total number of iterations of the Markov chain.

        Returns
        -------
        numpy.ndarray
            Numpy array of zeros of the required structure.
        """
        return np.zeros((total_number_of_iterations, number_of_particles, dimensionality_of_particle_space))

    def output_sample(self, sample, checkpoint_index):
        """
        Following completion of the Markov chain, print the sample to the output file.

        Parameters
        ----------
        sample : numpy.ndarray
            The sample generated by the Markov chain.
        checkpoint_index : int
            The index of the iteration through the list sampling checkpoints.
        """
        self._write_sample_to_file(sample, f"checkpoint_{checkpoint_index:02d}_sample_of_positions.npy")

    def get_sample(self, checkpoint_index):
        """
        In order to analyse the Markov chain in an external program, read the sample from the output file.

        Parameters
        ----------
        checkpoint_index : int
            The index of the iteration through the list sampling checkpoints.

        Returns
        ----------
        numpy.ndarray
            The sample generated by the Markov chain.
        """
        return self._read_sample_from_file(f"checkpoint_{checkpoint_index:02d}_sample_of_positions.npy")
