"""Module for the PressureSampler class."""
import numpy as np
from .observation_sampler import ObservationSampler
from potential.euclidean_subspace_potential import EuclideanSubspacePotential
from model_settings import number_of_particles, system_volume


class PressureSampler(ObservationSampler):
    """
    Class for taking observations of the hard-sphere pressure.
    """

    def __init__(self, output_directory: str):
        """
        The constructor of the PressureSampler class.

        Parameters
        ----------
        output_directory : str
            The filename onto which the sample is written at the end of the run.
        """
        super().__init__(output_directory)
        self.distance_between_measurements = None

    def get_empty_sample_array(self, total_number_of_iterations):
        """
        Generate array that stores the sample.

        Parameters
        ----------
        total_number_of_iterations : int
            The total number of iterations of the Markov chain.

        Returns
        -------
        numpy.ndarray
            Numpy array of zeros of the required structure.
        """
        return np.zeros((total_number_of_iterations, 1))

    def get_observation(self, momenta, positions, potential):
        """
        Returns an observation of the system for the given particle momenta and positions.  We estimate the pressure
            (in units of packing fraction) using Eq. (21) of J. Chem. Phys. 157, 234111 (2022) [DOI:10.1063/5.0126437].
            Note that we define the hard-disk pressure as beta P, where P is the pressure of the corresponding
            soft-sphere system at inverse temperature beta.  This results in the units of packing fraction.

        Parameters
        ----------
        momenta : None or numpy.ndarray
            None or a two-dimensional numpy array of size (number_of_particles, dimensionality_of_particle_space); each
            element is a float and represents one Cartesian component of the momentum of a single particle.
        positions : numpy.ndarray
            A two-dimensional numpy array of size (number_of_particles, dimensionality_of_particle_space); each element
            is a float and represents one Cartesian component of the position of a single particle. For Bayesian
            models, the entire positions array corresponds to the parameter; for the Ginzburg-Landau potential on a
            lattice, the entire positions array corresponds to the entire array of superconducting phase.
        potential : potential.potential.Potential
            An instance of the chosen child class of potential.euclidean_subspace_potential.EuclideanSubspacePotential.

        Returns
        -------
        float
            The observation of the pressure in units of packing fraction.
        """
        if not isinstance(potential, EuclideanSubspacePotential):
            raise ValueError(f"Give a EuclideanSubspacePotential class as the value for potential in the "
                             f"get_observation() method of {self.__class__.__name__}.")
        aggregate_pointer_hop_distance = potential.aggregate_pointer_hop_distance
        potential.aggregate_pointer_hop_distance = 0.0
        return (number_of_particles * (1.0 + aggregate_pointer_hop_distance / self.distance_between_measurements) /
                system_volume)

    def output_sample(self, sample, checkpoint_index):
        """
        Following completion of the Markov chain, print the sample to the output file.

        Parameters
        ----------
        sample : numpy.ndarray
            The sample generated by the Markov chain.
        checkpoint_index : int
            The index of the iteration through the list sampling checkpoints.
        """
        self._write_sample_to_file(sample, f"checkpoint_{checkpoint_index:02d}_sample_of_pressure.npy")

    def get_sample(self, checkpoint_index):
        """
        In order to analyse the Markov chain in an external program, read the sample from the output file.

        Parameters
        ----------
        checkpoint_index : int
            The index of the iteration through the list sampling checkpoints.

        Returns
        ----------
        numpy.ndarray
            The sample generated by the Markov chain.
        """
        return self._read_sample_from_file(f"checkpoint_{checkpoint_index:02d}_sample_of_pressure.npy")
