"""Module for the abstract Sampler class."""
from abc import ABCMeta, abstractmethod
import numpy as np
import os


class Sampler(metaclass=ABCMeta):
    """
    Abstract class for taking observations of the state of the system.
    """

    def __init__(self, **kwargs):
        """
        The constructor of the Sampler class.

        This class is designed for cooperative inheritance, meaning that it passes through all unused kwargs in the
        init to the next class in the MRO via super.

        Parameters
        ----------
        kwargs : Any
            Additional kwargs which are passed to the __init__ method of the next class in the MRO.

        Raises
        ------
        base.exceptions.ConfigurationError
            If type(output_directory) is not str.
        """
        super().__init__(**kwargs)

    @abstractmethod
    def get_empty_sample_array(self, *args):
        """
        Generates a numpy array or Python list to store the sample.
        """
        raise NotImplementedError

    @abstractmethod
    def get_observation(self, *args):
        """
        Returns an observation of the state of the system.
        """
        raise NotImplementedError

    @abstractmethod
    def output_sample(self, sample, checkpoint_index, output_directory):
        """
        Following completion of the Markov process, print the sample to the output file.

        Parameters
        ----------
        sample : numpy.ndarray
            The sample generated by the Markov chain.
        checkpoint_index : int
            The index of the iteration through the list sampling checkpoints.
        output_directory : str
            The name of the directory into which the sample file is written at the end of the run.
        """
        raise NotImplementedError

    @abstractmethod
    def get_sample(self, checkpoint_index, output_directory):
        """
        To analyse the Markov chain in an external program, read the sample from the output file.

        Parameters
        ----------
        checkpoint_index : int
            The index of the iteration through the list sampling checkpoints.
        output_directory : str
            The name of the directory into which the sample file is written at the end of the run.

        Returns
        ----------
        numpy.ndarray
            The sample generated by the Markov chain.
        """
        raise NotImplementedError

    @staticmethod
    def _write_sample_to_file(sample, sample_file_string, output_directory):
        np.save(os.path.join(os.getcwd(), output_directory, sample_file_string),
                np.reshape(sample, (sample.shape[0], -1)))

    @staticmethod
    def _read_sample_from_file(sample_file_string, output_directory):
        return np.load(output_directory + '/' + sample_file_string)
