"""Module for the SingleParticlePositionSampler class."""
from model_settings import size_of_particle_space
from .observation_sampler import ObservationSampler
import numpy as np


class SingleParticlePositionSampler(ObservationSampler):
    """
    Class for taking observations of a single particle position.
    """

    def __init__(self, particle_index: int = 0):
        """
        The constructor of the SingleParticlePositionSampler class.

        Parameters
        ----------
        particle_index : int
            Index of particle to sample position.
        """
        super().__init__()
        self._particle_index = particle_index

    def get_empty_sample_array(self, total_number_of_iterations):
        """
        Generate array that stores the sample.

        Parameters
        ----------
        total_number_of_iterations : int
            The total number of iterations of the Markov chain.

        Returns
        -------
        numpy.ndarray
            Numpy array of zeros of the required structure.
        """
        return np.zeros((total_number_of_iterations, 1))

    def get_observation(self, momenta, positions, potential):
        """
        Returns an observation of the system for the given particle momenta and positions.

        Parameters
        ----------
        momenta : None or numpy.ndarray
            None or a two-dimensional numpy array of size (number_of_particles, dimensionality_of_particle_space); each
            element is a float and represents one Cartesian component of the momentum of a single particle.
        positions : numpy.ndarray
            A two-dimensional numpy array of size (number_of_particles, dimensionality_of_particle_space); each element
            is a float and represents one Cartesian component of the position of a single particle. For Bayesian
            models, the entire positions array corresponds to the parameter; for the Ginzburg-Landau potential on a
            lattice, the entire positions array corresponds to the entire array of superconducting phase.
        potential : float or potential.potential.Potential
            If a float, the current value of the potential; otherwise, an instance of the chosen child class of
            potential.potential.Potential.

        Returns
        -------
        float
            The observation of one of the particles' positions.
        """
        return positions[self._particle_index] % size_of_particle_space

    def output_sample(self, sample, checkpoint_index, output_directory):
        """
        Following completion of the Markov chain, print the sample to the output file.

        Parameters
        ----------
        sample : numpy.ndarray
            The sample generated by the Markov chain.
        checkpoint_index : int
            The index of the iteration through the list sampling checkpoints.
        output_directory : str
            The name of the directory into which the sample file is written at the end of the run.
        """
        self._write_sample_to_file(sample, f"checkpoint_{checkpoint_index:02d}"
                                           f"_sample_of_single_particle_position.npy", output_directory)

    def get_sample(self, checkpoint_index, output_directory):
        """
        In order to analyse the Markov chain in an external program, read the sample from the output file.

        Parameters
        ----------
        checkpoint_index : int
            The index of the iteration through the list sampling checkpoints.
        output_directory : str
            The name of the directory into which the sample file is written at the end of the run.

        Returns
        ----------
        numpy.ndarray
            The sample generated by the Markov chain.
        """
        return self._read_sample_from_file(
            f"checkpoint_{checkpoint_index:02d}_sample_of_single_particle_position.npy", output_directory)
