"""Module for the StateSpaceVelocitySampler class."""
from base.exceptions import ConfigurationError
from model_settings import size_of_particle_space
from potential.euclidean_subspace_potential import EuclideanSubspacePotential
from .observation_sampler import ObservationSampler
import numpy as np


class StateSpaceVelocitySampler(ObservationSampler):
    """
    Class for taking observations of the state space velocity.
    """

    def __init__(self, output_directory: str):
        """
        The constructor of the StateSpaceVelocitySampler class.

        This class is designed for cooperative inheritance, meaning that it passes through all unused kwargs in the
        init to the next class in the MRO via super.

        Parameters
        ----------
        output_directory : str
            The filename onto which the sample is written at the end of the run.

        Raises
        ------
        base.exceptions.ConfigurationError
            If dimensionality_of_particle_space does not equal 1.
        """
        super().__init__(output_directory)
        if len(size_of_particle_space) != 1:
            raise ConfigurationError(f"{self.__class__.__name__} only supports 1D systems.")

    def get_empty_sample_array(self, total_number_of_iterations):
        """
        Generate array that stores the sample.

        Parameters
        ----------
        total_number_of_iterations : int
            The total number of iterations of the Markov chain.

        Returns
        -------
        numpy.ndarray
            Numpy array of zeros of the required structure.
        """
        return np.zeros((total_number_of_iterations, 1))

    def get_observation(self, momenta, positions, potential):
        """
        Returns an observation of the system for the given particle momenta and positions.

        Parameters
        ----------
        momenta : None or numpy.ndarray
            None or a two-dimensional numpy array of size (number_of_particles, dimensionality_of_particle_space); each
            element is a float and represents one Cartesian component of the momentum of a single particle.
        positions : numpy.ndarray
            A two-dimensional numpy array of size (number_of_particles, dimensionality_of_particle_space); each element
            is a float and represents one Cartesian component of the position of a single particle. For Bayesian
            models, the entire positions array corresponds to the parameter; for the Ginzburg-Landau potential on a
            lattice, the entire positions array corresponds to the entire array of superconducting phase.
        potential : potential.potential.Potential
            An instance of the chosen child class of potential.euclidean_subspace_potential.EuclideanSubspacePotential.

        Returns
        -------
        float
            The observation of the state space velocity.
        """
        if not isinstance(potential, EuclideanSubspacePotential):
            raise ValueError(f"Give a EuclideanSubspacePotential class as the value for potential in the "
                             f"get_observation() method of {self.__class__.__name__}.")
        state_space_displacement, total_event_distance = (potential.state_space_displacement,
                                                          potential.total_event_distance)
        potential.state_space_displacement = 0.0
        potential.total_event_distance = 0.0
        return 0.0 if total_event_distance == 0.0 else state_space_displacement / total_event_distance

    def output_sample(self, sample, checkpoint_index):
        """
        Following completion of the Markov chain, print the sample to the output file.

        Parameters
        ----------
        sample : numpy.ndarray
            The sample generated by the Markov chain.
        checkpoint_index : int
            The index of the iteration through the list sampling checkpoints.
        """
        self._write_sample_to_file(sample,f"checkpoint_{checkpoint_index:02d}_sample_of_state_space_velocity.npy")

    def get_sample(self, checkpoint_index):
        """
        In order to analyse the Markov chain in an external program, read the sample from the output file.

        Parameters
        ----------
        checkpoint_index : int
            The index of the iteration through the list sampling checkpoints.

        Returns
        ----------
        numpy.ndarray
            The sample generated by the Markov chain.
        """
        return self._read_sample_from_file(f"checkpoint_{checkpoint_index:02d}_sample_of_state_space_velocity.npy")
