from markov_chain_diagnostics import get_sample_mean_and_error
import importlib
import matplotlib
import os
import sample_getter
import sys

# Add the directory that contains the module plotting_functions to sys.path
this_directory = os.path.dirname(os.path.abspath(__file__))
src_directory = os.path.abspath(this_directory + "/../")
sys.path.insert(0, src_directory)
helper_methods = importlib.import_module("helper_methods")
parsing = importlib.import_module("base.parsing")
strings = importlib.import_module("base.strings")


def main(config_file_string):
    """
    This script tests pressure estimates generated by hard-disk code against published at the URL below:
        https://github.com/jellyfysh/HistoricDisks/blob/master/DigitizedData/ThisWork.csv

    N.B. config_file_string is the location of the config file.
    """
    matplotlib.rcParams['text.latex.preamble'] = r"\usepackage{amsmath}"
    config = parsing.read_config(parsing.parse_options([config_file_string]).config_file)
    (config_file_mediator, potential, _, samplers, sample_directory, temperature, number_of_equilibration_iterations,
     _, number_of_particles, _) = helper_methods.get_basic_config_data(config_file_string)

    if potential == "hard_disk_potential":
        if not (len(samplers) == 1 and samplers[0] == "pressure_sampler"):
            raise ValueError("This script tests hard-disk code against pressure estimates.  Please give only the value "
                             "pressure_sampler for samplers in the Mediator section.")
    else:
        raise ValueError("This script is designed to test hard-disk code.  Please give only the value "
                         "hard_disk_potential for potential in the Mediator section.")

    disk_radius = parsing.get_value(config, "HardDiskPotential", "disk_radius")
    sample_mean, sample_error = get_sample_mean_and_error(
        sample_getter.get_pressure(sample_directory, temperature, 0, 0,
                                   number_of_particles, number_of_equilibration_iterations).flatten())
    print(f"Pressure = {sample_mean * (2.0 * disk_radius) ** 2} +- {sample_error * (2.0 * disk_radius) ** 2}")
    packing_fraction = parsing.get_value(config, "HardDiskPotential", "packing_fraction")
    packing_fraction_after_decimal_point = str(packing_fraction).split('.')[1].ljust(3, '0')[:3]
    with open(f"{sample_directory}/packing_fraction_point_{packing_fraction_after_decimal_point}.dat",
              'w') as output_file:
        output_file.write(f"Pressure = {sample_mean * (2.0 * disk_radius) ** 2} +- "
                          f"{sample_error * (2.0 * disk_radius) ** 2}\n")


if __name__ == '__main__':
    main(sys.argv[1])
