#include <iostream>
#include <random>
#include <cmath>
#include <complex>
#include <stdio.h>
#include <algorithm>
#include <array>
#include <vector>
#include "get_next_event.hpp"
#include <cassert>
#include <pybind11/pybind11.h>

struct next_event{
  double shortest_distance_to_next_event;
  int vetoing_index;
};


// struct next_event get_next_kinetic_event(int active_particle_index, int east_neighbour_index, int west_neighbour_index, int number_of_quantum_particles, int number_of_timeslices, 
//     double active_particle_position, double east_neighbour_position, double west_neighbour_position, double mass,
//     double timestep, int movement_direction){


//     struct next_event proposed_kinetic_event;

//     double shortest_distance_to_next_kinetic_event = 1.0e+10;
//     int vetoing_index = 0;
//     double initial_position = active_particle_position;

//     for (int neighbour = 0; neighbour < 2; neighbour++){
//         std::default_random_engine generator;
//         std::uniform_real_distribution<double> dist(0.0, 1.0);
//         // Use dist to transform the random unsigned int generated by gen into a 
//         // double in [0.0, 1.0). Each call to dist(gen) generates a new random double.
//         double uphill_energy =  -log(dist(generator));
//         //std::cout << "kinetic uphill energy = " << uphill_energy << std::endl;

//         double neighbour_position;
//         int possible_veto;
//         if (neighbour == 0){
//             //std::cout << "west" << std::endl;
//             neighbour_position = west_neighbour_position;
//             possible_veto = west_neighbour_index;
//         }
//         else {
//            // std::cout << "east" << std::endl;
//             neighbour_position = east_neighbour_position;
//             possible_veto = east_neighbour_index;
//         }

//         double intermediate_position;
//         double bottom_of_well = neighbour_position;
//         if((movement_direction > 0  && initial_position < bottom_of_well)
//         || (movement_direction < 0 && initial_position > bottom_of_well)){
//             intermediate_position = bottom_of_well;
//         }
//         else {
//             intermediate_position = initial_position;
//         }

//         double diff = intermediate_position - neighbour_position;
//         double initial_action = 0.5 * (mass / timestep) * pow(diff, 2);
//         double final_action = uphill_energy + initial_action;
//         //std::cout << "final_action = " << final_action << std::endl;

//         double a = 0.5 * mass / timestep;
//         double b = - mass / timestep * neighbour_position;
//         double c = a * pow(neighbour_position, 2) - final_action;

//         std::vector<double> roots_arr; 
//         roots_arr = get_real_quadratic_roots(a, b, c);

//         double final_position = get_final_position_of_single_well_event(movement_direction, roots_arr);
//         //std::cout << "final_position = " << final_position << std::endl;


//         double distance_to_candidate_kinetic_event = std::abs((final_position - initial_position));
//         //std::cout << "candidate kinetic event dist = " << distance_to_candidate_kinetic_event << std::endl;

//         if (distance_to_candidate_kinetic_event < shortest_distance_to_next_kinetic_event){
//             shortest_distance_to_next_kinetic_event = distance_to_candidate_kinetic_event;
//             vetoing_index = possible_veto;
//         } 
//     }

//     proposed_kinetic_event.shortest_distance_to_next_event = shortest_distance_to_next_kinetic_event;
//     proposed_kinetic_event.vetoing_index = vetoing_index;

//   return proposed_kinetic_event;

// }

struct next_event get_next_kinetic_event(int active_particle_index, int east_neighbour_index, int west_neighbour_index, int number_of_quantum_particles, int number_of_timeslices, 
    double active_particle_position, double east_neighbour_position, double west_neighbour_position, double mass,
    double timestep, int movement_direction, double U_west,
    double U_east){

    struct next_event proposed_kinetic_event;

    proposed_kinetic_event.shortest_distance_to_next_event = 1.0e10;
    proposed_kinetic_event.vetoing_index = number_of_quantum_particles * number_of_timeslices; // should error if returned

    double initial_position = active_particle_position;

    for(int neighbour = 0; neighbour < 2; neighbour++){
        // std::random_device rd;  // Will be used to obtain a seed for the random number engine
        // std::mt19937 generator(rd()); // Standard mersenne_twister_engine seeded with rd()
        // std::uniform_real_distribution<> dist(0.0, 1.0);
        // double uphill_energy = -log(dist(generator));
        //std::cout << "-ln(U) = " << uphill_energy << std::endl;
        double uphill_energy;
        double neighbour_position;
        int possible_veto;
        if(neighbour == 0){
            neighbour_position = west_neighbour_position;
            possible_veto = west_neighbour_index;
            uphill_energy = U_west;
        }
        else{
            neighbour_position = east_neighbour_position;
            possible_veto = east_neighbour_index;
            uphill_energy = U_east;

        }

        double bottom_of_well = neighbour_position;
        double intermediate_position;
        if((movement_direction > 0 && initial_position < bottom_of_well)||
        (movement_direction < 0 && initial_position > bottom_of_well)){
            intermediate_position = bottom_of_well;
        }
        else{
            intermediate_position = initial_position;
        }
        double diff = intermediate_position - neighbour_position;
        double initial_action = 0.5 * (mass /  timestep) * pow(diff, 2);
        double final_action = uphill_energy + initial_action;

        double a = 0.5 * mass / timestep;
        double b = -mass / timestep * neighbour_position;
        double c = a * pow(neighbour_position, 2) - final_action;

        std::vector<double> roots = get_real_quadratic_roots(a, b, c);
        double final_position = get_final_position_of_single_well_event(movement_direction, roots);
        //std::cout << "kinetic: final: " << final_position << " initial: " << initial_position << std::endl;
        double distance_to_possible_event = std::abs(final_position - initial_position);

        //std::cout << "c++ proposed kinetic: " << distance_to_possible_event << ", " << possible_veto << std::endl;
        if(distance_to_possible_event < proposed_kinetic_event.shortest_distance_to_next_event){
            proposed_kinetic_event.shortest_distance_to_next_event = distance_to_possible_event;
            proposed_kinetic_event.vetoing_index = possible_veto;
        }
    }
    return proposed_kinetic_event;
}
struct next_event get_next_event(int active_particle_index, int east_neighbour_index, int west_neighbour_index, int number_of_quantum_particles, int number_of_timeslices, 
    double active_particle_position, double east_neighbour_position, double west_neighbour_position, double mass,
    double timestep, int movement_direction, double anharmonicity, double omega_squared, double magnitude_of_double_well_position, double U_west,
    double U_east, double U_potential){
    


    struct next_event shortest_event = get_next_kinetic_event(active_particle_index, east_neighbour_index, west_neighbour_index,
        number_of_quantum_particles, number_of_timeslices, active_particle_position, east_neighbour_position,
        west_neighbour_position, mass, timestep, movement_direction, U_west, U_east);  
    //std::cout << "accepted kinetic: " << shortest_event.shortest_distance_to_next_event << ", " << shortest_event.vetoing_index << std::endl;

    double initial_position = active_particle_position;
    // std::default_random_engine generator;
    // std::uniform_real_distribution<double> dist(0.0, 1.0);
    //     // Use dist to transform the random unsigned int generated by gen into a 
    //     // double in [0.0, 1.0). Each call to dist(gen) generates a new random double.
    // double uphill_energy =  -log(dist(generator));
    double uphill_energy = U_potential;
    // //std::cout << "potential uphill energy = " << uphill_energy << std::endl;
    double epsilon = 1e-10;
    double bottom_of_well;

    if(std::abs(anharmonicity) <= epsilon || std::abs(omega_squared) <= epsilon){
        bottom_of_well = 0.0;
    }
    else{
        //////////////////////////////////////////////////////////////
        // vvvvvvvvvvvvvvvv
        if(std::abs(initial_position) >= epsilon){
            if(initial_position < 0.0){
                bottom_of_well = -magnitude_of_double_well_position;
            }
            else{
                bottom_of_well = magnitude_of_double_well_position;
            }
            //bottom_of_well = magnitude_of_double_well_position * (initial_position / std::abs(initial_position));
        }
        else{
            if(movement_direction > 0){
                bottom_of_well = magnitude_of_double_well_position;
            }
            else{
                bottom_of_well = -magnitude_of_double_well_position;
            }
        }
    }
    // ^^^^^^^^^^^^^^^^
    /////////////////////////////////////////////////////////////////////

    double intermediate_position;
    if ((movement_direction > 0  && initial_position < bottom_of_well)
        || (movement_direction < 0 && initial_position > bottom_of_well)){
        intermediate_position = bottom_of_well;
    }
    else{
        intermediate_position = initial_position;
    }

    double initial_action = 0.5 * mass * timestep * omega_squared * pow(intermediate_position, 2)
                            + timestep * anharmonicity * pow(intermediate_position, 4);
    double final_action = uphill_energy + initial_action;
    //std::cout << "final_action = " << final_action << std::endl;


    std::vector<double> real_roots_arr;
    std::vector<std::complex<double>> roots_arr; 
    if(std::abs(anharmonicity) <= 0){ 
        real_roots_arr = get_harmonic_potential_roots(mass, timestep, omega_squared, final_action);
    }
    ///////////////////////////////////////////////
    // vvvvvvvvvvvvvvvvvvvv
    else{
        roots_arr = get_anharmonic_potential_roots(mass, timestep, anharmonicity, omega_squared, final_action);
    }
    // ^^^^^^^^^^^^^^^^^^^^^
    //////////////////////////////////////////////////
    double final_position;

    ////////////////////////////////////////////////////////////////////
    // vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
    if(anharmonicity > 0.0 && 0.0 > omega_squared){
        bool real_roots = check_all_roots_real(roots_arr);
        if(real_roots){
            real_roots_arr = get_real_elements(roots_arr);
            final_position = get_final_position_of_non_tunnel_event(intermediate_position, movement_direction, real_roots_arr);
        }
        else{
            if((movement_direction > 0 && intermediate_position > 0.0) ||
                (movement_direction < 0 && intermediate_position < 0.0)){
                //std::cout << "roots_vect is size " << roots_vect.size() << std::endl;
                real_roots_arr = get_real_elements(roots_arr);
                //std::cout << "line 188 passed std::vector<double> real_roots_arr to get_final_position_of_single_well_event()" << std::endl;
                final_position = get_final_position_of_single_well_event(movement_direction, real_roots_arr);
                }
            else{
                double remaining_barrier_height = get_barrier_height(intermediate_position, timestep, mass, anharmonicity,
                                                    omega_squared);
                bottom_of_well *= -1;
                intermediate_position = bottom_of_well;
                final_action -= remaining_barrier_height;
                //std::cout << "final_action = " << final_action << std::endl;

                roots_arr = get_anharmonic_potential_roots(mass, timestep, anharmonicity, omega_squared, final_action);
                bool real_roots = check_all_roots_real(roots_arr);
            
                if(real_roots){
                    std::vector<double> real_roots_arr = get_real_elements(roots_arr);
                    final_position = get_final_position_of_non_tunnel_event(intermediate_position, movement_direction, real_roots_arr);
                }
                else{
                    std::vector<double> real_roots_arr = get_real_elements(roots_arr);
                    //std::cout << "line 203 passed std::vector<double> real_roots_arr to get_final_position_of_single_well_event()" << std::endl;
                    final_position = get_final_position_of_single_well_event(movement_direction, real_roots_arr);
                }
            }
        }
    }
    // ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    //////////////////////////////////////////////////////////////////
    else{
        //std::vector<double> real_roots_arr = get_real_elements(roots_vect);
        //std::cout << "line 211 passed std::vector<double> real_roots_arr to get_final_position_of_single_well_event()" << std::endl;
        final_position = get_final_position_of_single_well_event(movement_direction, real_roots_arr);
    }
    double distance_to_next_factor_event = std::abs(final_position - initial_position);
    //std::cout << "distance to next potential event " << distance_to_next_factor_event << std::endl;
    //std::cout << "distance to next kinetic event " << next_kinetic_event.shortest_distance_to_next_event << std::endl;
    //std::cout << "c++ potential: " << distance_to_next_factor_event << ", " << active_particle_index << std::endl;

    if(distance_to_next_factor_event < shortest_event.shortest_distance_to_next_event){
        shortest_event.shortest_distance_to_next_event = distance_to_next_factor_event;
        shortest_event.vetoing_index = active_particle_index;
    }
    
    //std::cout << "c++ accepted event: " << shortest_event.shortest_distance_to_next_event << ", " << shortest_event.vetoing_index << std::endl;

    return shortest_event;
}
////////////////////////////////////
// vvvvvvvvvvv
double get_barrier_height(double position, double timestep, double mass, double anharmonicity, double omega_squared){
  return std::abs(-(timestep * anharmonicity * pow(position, 4) + 0.5 * mass * timestep * omega_squared * pow(position, 2)));
}

std::vector<double> get_real_elements(std::vector<std::complex<double>> complex_arr){

    double epsilon = 1e-10;
    std::vector<double> real_arr;
    for(long unsigned int i = 0; i < complex_arr.size(); i++){
        std::complex<double> ith_root = complex_arr.at(i);
        if(std::abs(ith_root.imag()) <= epsilon){
            real_arr.push_back(ith_root.real());
        }
    }

    return real_arr;
}

double get_final_position_of_non_tunnel_event(double position, int movement_direction, std::vector<double> roots){

    std::sort(roots.begin(), roots.end());

    if(position < 0.0){
        if(movement_direction > 0){
            return roots.at(1);
        }
        else{
            return roots.at(0);
        }
    }
    else{
        if(movement_direction > 0){
            return roots.at(3);
        }
        else{
            return roots.at(2);
        }
    }
}


bool check_all_roots_real(std::vector<std::complex<double>> roots){
    bool real_roots = true;
    for(int i = 0; i < 4; i++){
        std::complex<double> ith_root = roots.at(i);
        if(ith_root.imag() != 0.0){
            real_roots = false;
        }
    }
    return real_roots;
}

// ^^^^^^^^^^^^^^
///////////////////////////////////

std::vector<double> get_harmonic_potential_roots(double mass, double timestep, double omega_squared, double final_action){
  
    std::vector<double> roots; 
    double a = 0.5 * mass * timestep * omega_squared;
    double b = 0.0;
    double c = -final_action;

    roots = get_real_quadratic_roots(a, b, c);
    return roots;
}

///////////////////////////////////////////
// vvvvvvvvvvvvvvvvvvvvvvvvvvv
std::vector<std::complex<double>> get_anharmonic_potential_roots(double mass, double timestep, double anharmonicity,
                      double omega_squared, double final_action){
    std::vector<std::complex<double>> roots_U; 
    std::vector<std::complex<double>> roots; 
    double a = timestep * anharmonicity;
    double b = 0.5 * mass * timestep * omega_squared;
    double c = -final_action;

    roots_U = get_quadratic_roots(a, b, c);

    roots.push_back(sqrt(roots_U.at(0))); 
    roots.push_back(-sqrt(roots_U.at(0)));
    roots.push_back(sqrt(roots_U.at(1))); 
    roots.push_back(-sqrt(roots_U.at(1)));

    return roots;
  
}

std::vector<std::complex<double>> get_quadratic_roots(double a, double b, double c){
    // complex type because we could sqrt a -ve number here
    std::vector<std::complex<double>> roots; 
    std::complex<double> discriminant = pow(b, 2) - 4.0 * a * c;
    //std::cout << "a,b,c: " << a << ", " << b << ", " << c << std::endl;
    //std::cout << "disc:" << discriminant << std::endl;
    roots.push_back((-b + std::sqrt(discriminant)) / (2.0 * a));
    //std::cout << "root +:" << (-b + std::sqrt(discriminant)) / (2.0 * a) << std::endl;
    roots.push_back((-b - std::sqrt(discriminant)) / (2.0 * a));
    //std::cout << "root -:" << (-b - std::sqrt(discriminant)) / (2.0 * a) << std::endl;


    return roots;
}
// ^^^^^^^^^^^^^^^^^^^^^^^^^^^
//////////////////////////////////////

// std::vector<double> get_real_quadratic_roots(double a, double b, double c){

//     std::vector<double> roots; 
//     double discriminant = pow(b, 2) - 4.0 * a * c;
//     //std::cout << "real a,b,c: " << a << ", " << b << ", " << c << std::endl;
//     //std::cout << "disc:" << discriminant << std::endl;
//     roots.push_back((-b + std::sqrt(discriminant)) / (2.0 * a));
//     //std::cout << "root +:" << (-b + std::sqrt(discriminant)) / (2.0 * a) << std::endl;
//     roots.push_back((-b - std::sqrt(discriminant)) / (2.0 * a));
//     //std::cout << "root -:" << (-b - std::sqrt(discriminant)) / (2.0 * a) << std::endl;

//     return roots;
// }

std::vector<double> get_real_quadratic_roots(double a, double b, double c){
    std::vector<double> roots;

    //std::cout << "a: " << a << ", b: " << b << " c: " << c << std::endl;

    double discriminant = pow(b, 2) - 4.0 * a * c;
    roots.push_back((-b + std::sqrt(discriminant)) / (2.0 * a));
    roots.push_back((-b - std::sqrt(discriminant)) / (2.0 * a));

    //std::cout << "disc: " << discriminant << std::endl;
    return roots;
}

// double get_final_position_of_single_well_event(int movement_direction, std::vector<double> roots){
//     if(roots.size() == 2){
//         if ((movement_direction > 0) && (roots.at(0) > roots.at(1))){
//             return roots.at(0);
//         }
//         else if ((movement_direction > 0) && (roots.at(0) < roots.at(1))){
//             return roots.at(1);
//         }
//         else if ((movement_direction < 0) && (roots.at(0) < roots.at(1))){
//             return roots.at(0);
//         }
//         else{
//             return roots.at(1);
//         }
//     }
//     else{
//     throw std::invalid_argument("Invalid argument to double get_final_position_of_single_well_event(int movement_direction, std::vector<double> roots), \n std::vector<double> roots should have length 2");
//     }
// }

double get_final_position_of_single_well_event(int movement_direction, std::vector<double> roots){
    assert(roots.size() == 2);

    std::sort(roots.begin(), roots.end());
    // for(double r: roots){
    //     std::cout << r << ", ";
    // }
    // std::cout << std::endl;
    double return_root;

    if(movement_direction > 0){
       return_root = roots.at(1);
    }
    else{
        return_root = roots.at(0);
    }
    return return_root;
}


int main() {
    // int active_particle_index = 5;
    // int east_neighbour_index = 6;
    // int west_neighbour_index = 4;
    // int number_of_quantum_particles = 1;
    // int number_of_timeslices = 50; 
    // double active_particle_position = 1.23;
    // double east_neighbour_position = 0.05;
    // double west_neighbour_position = 1.1;
    // double mass = 0.5;
    // double timestep = 1.0;
    // int movement_direction = 1.0;
    // double anharmonicity = 1.0;
    // double omega_squared = -15.0;
    // double magnitude_of_double_well_position = 1.37;
    // struct next_event test = get_next_event(active_particle_index, east_neighbour_index, west_neighbour_index, number_of_quantum_particles,
    //     number_of_timeslices, active_particle_position, east_neighbour_position, west_neighbour_position, mass,
    //     timestep, movement_direction, anharmonicity, omega_squared, magnitude_of_double_well_position);

    // std::cout << test.shortest_distance_to_next_event << std::endl;
    // std::cout << test.vetoing_index << std::endl;


    return 0;
} 